# Generated by Django 4.0.4 on 2022-05-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_caption', models.CharField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploaded_videos')),
                ('video_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_tags', models.TextField(blank=True, max_length=2000, null=True)),
                ('video_likes', models.IntegerField(blank=True, null=True)),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
