# Generated by Django 4.0.4 on 2022-05-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_usrregmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrRegModel',
        ),
    ]
