# Generated by Django 4.0.4 on 2022-05-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_delete_usrregmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_likes',
        ),
    ]
